DROP DATABASE IF EXISTS lunch_db;
CREATE DATABASE lunch_db;

USE lunch_db;

CREATE TABLE burgers (
  id INT(11) AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  devoured BOOLEAN DEFAULT false,
  PRIMARY KEY (id)
);